name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install minimal deps
      run: |
        python -m pip install --upgrade pip
        pip install numpy gymnasium

    - name: Run env smoke test
      run: |
        python -c "import runpy; runpy.run_path('tests/test_generic_env.py', run_name='__main__')"
        python -c "import runpy; runpy.run_path('tests/smoke_env.py', run_name='__main__')"

    - name: Run flake8 (optional)
      run: |
        pip install flake8
        flake8 --max-line-length=120 || true
